import re
import io
import zipfile
import requests
import json
import base64
import logging
from typing import Dict, List, Tuple, Optional
from github import Github, UnknownObjectException, InputGitTreeElement, GithubException

logger = logging.getLogger(__name__)
OLLAMA_URL = "http://localhost:11434/api/generate"

# --- 1. Parsing & Infrastructure ---
def parse_strict_logs(lines_iter) -> Dict[str, str]:
    """Strict parser for '# Filename: path' format."""
    files = {}
    current_file = None
    current_content = []
    header_re = re.compile(r'^# Filename:\s*(.+)$', re.IGNORECASE)
    
    for line in lines_iter:
        line = line.rstrip('\n\r')
        match = header_re.match(line.strip())
        if match:
            if current_file:
                files[current_file] = "".join(current_content).strip() + '\n'
            current_file = match.group(1).strip()
            current_content = []
        else:
            if current_file:
                current_content.append(line + '\n')
                
    if current_file:
        files[current_file] = "".join(current_content).strip() + '\n'
    return files

def extract_zip(file_bytes: bytes) -> Dict[str, str]:
    """Robust extraction of text files from ZIP archives."""
    files = {}
    try:
        with zipfile.ZipFile(io.BytesIO(file_bytes)) as z:
            for info in z.infolist():
                if info.is_dir() or info.filename.startswith('.') or '__MACOSX' in info.filename:
                    continue
                try:
                    content = z.read(info.filename).decode('utf-8')
                    files[info.filename] = content
                except UnicodeDecodeError:
                    pass # Silently skip binaries
    except zipfile.BadZipFile:
        logger.error("Invalid Zip File uploaded.")
    return files

# --- 2. Local LLM (Llama 3) Integration ---
def check_ollama_status() -> bool:
    try:
        res = requests.get("http://localhost:11434/api/tags", timeout=2)
        return res.status_code == 200
    except: return False

def call_ollama(prompt: str, model: str = "llama3") -> Optional[str]:
    try:
        response = requests.post(OLLAMA_URL, json={
            "model": model, "prompt": prompt, "stream": False, "format": "json"
        }, timeout=180)
        if response.status_code == 200:
            return response.json().get("response", "")
        return None
    except Exception as e:
        logger.error(f"Ollama inference failed: {e}")
        return None

def analyze_code(file_path: str, content: str) -> List[Dict[str, str]]:
    """Scans code for bugs and requests full corrected code via Llama 3."""
    # Truncate to ~6000 tokens to respect local LLM context windows
    safe_content = content[:24000] if len(content) > 24000 else content
    ext = file_path.split('.')[-1] if '.' in file_path else ""
    
    prompt = f"""You are an elite code reviewer. Analyze this {ext} code for bugs, logic errors, or vulnerabilities.
File: {file_path}
```{ext}
{safe_content}
```
If issues exist, return a JSON array: [{{"bug": "description", "corrected_code": "the FULL corrected code"}}].
If perfect, return []. Return ONLY valid JSON."""
    
    raw_res = call_ollama(prompt)
    if not raw_res: return []
    
    try:
        clean_res = raw_res.strip().replace("```json", "").replace("```", "").strip()
        return json.loads(clean_res)
    except json.JSONDecodeError:
        return []

def generate_readme(files: Dict[str, str]) -> str:
    file_list = ", ".join(list(files.keys())[:20])
    prompt = f"""Generate a professional, comprehensive README.md in Markdown for a project containing: {file_list}. 
    Include Overview, Features, and Setup instructions."""
    return call_ollama(prompt) or "# Project README\n\nGenerated by AI Bridge."

def generate_commit_message(files: Dict[str, str]) -> str:
    summary = ", ".join([f"{k}" for k in list(files.keys())[:10]])
    prompt = f"""Write a concise, professional Git commit message for updates to: {summary}."""
    return call_ollama(prompt) or "feat: autonomous pipeline update"

# --- 3. GitHub Atomic Commits ---
def commit_to_github(pat: str, repo_name: str, is_private: bool, description: str, 
                     files_dict: Dict[str, str], commit_msg: str, readme_content: str) -> Tuple[bool, str, Optional[str]]:
    if readme_content:
        files_dict["README.md"] = readme_content

    try:
        g = Github(pat)
        user = g.get_user()
        _ = user.login # Force auth check
        
        try: repo = user.get_repo(repo_name)
        except UnknownObjectException: repo = user.create_repo(repo_name, private=is_private, description=description)
            
        default_branch = repo.default_branch
        try:
            ref = repo.get_git_ref(f"heads/{default_branch}")
            sha = ref.object.sha
            commit = repo.get_git_commit(sha)
            base_tree = commit.tree
            parents = [commit]
        except GithubException as e:
            if e.status in (404, 409): base_tree, parents = None, []
            else: raise e
                
        tree_elements = []
        for path, content in files_dict.items():
            b64 = base64.b64encode(content.encode('utf-8')).decode('ascii')
            blob = repo.create_git_blob(b64, "base64")
            tree_elements.append(InputGitTreeElement(path, "100644", "blob", sha=blob.sha))
            
        new_tree = repo.create_git_tree(tree_elements, base_tree)
        new_commit = repo.create_git_commit(commit_msg, new_tree, parents)
        
        if parents: ref.edit(new_commit.sha)
        else: repo.create_git_ref(f"refs/heads/{default_branch}", new_commit.sha)
            
        return True, repo.html_url, None
    except GithubException as e:
        err = e.data.get('message', str(e)) if hasattr(e, 'data') and e.data else str(e)
        return False, "GitHub API Error", err
    except Exception as e:
        return False, "Pipeline Error", str(e)
